apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: europe-west1-docker.pkg.dev/dev-demo-proj-1-id/my-artifact-repo/testimg:63
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  selector:
    app: myweb
  ports:
    - protocol: TCP
      port: 8080   # Service port
      targetPort: 8080  # Container port
  type: ClusterIP
