apiVersion: argoproj.io/v1alpha1 # This file will create ArgoCD application via CDR
kind: Application
metadata:
  name: my-python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Karthickramasamy007/Git_Ops_ArgoCD
    targetRevision: HEAD
    path: example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: my-python-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false