apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example-app
  annotations:
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: aimvector/python:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/credentials.json  # Correct path for GCP service account

      volumeMounts:
        - name: gcp-service-account
          mountPath: /secret
          readOnly: true  # Ensures security by making it read-only

    volumes:
      - name: gcp-service-account
        secret:
          secretName: allow-gcp-resource-create-and-manage  # This should be the secret containing the service account JSON
          items:
            - key: credentials.json
              path: credentials.json  # Mount it as /secret/credentials.json
