apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: europe-west1-docker.pkg.dev/dev-demo-proj-1-id/my-artifact-repo/testimg:123
      imagePullSecrets:
      - name: gcr-json-key
