apiVersion: v1
kind: Namespace
metadata:
  name: my-python-app

# kubectl create secret generic my-ke-secret --from-file=C:\Users\karth\Downloads\dev-demo-proj-1-id-343d99591709.json -n my-python-app
